### ISSUE TITLE
Add tracks endpoints

### ISSUE THREAD

**Issue by manuporto** [tallerify/shared-server#23]

**Comment by abrden** [comment]
- [ ] Complete track db model

**Comment by abrden** [comment]
What's missing
- [ ] Tests for like
- [ ] Tests for dislike
- [ ] Don't repeat like entry when like request is duplicated
- [ ] What happens if we dislike something that was never liked?
- [ ] Tests for track popularity
- [ ] Half implementation and tests for track rating
- [ ] User favorites endpoint

**Comment by abrden** [comment]
> What happens if we dislike something that was never liked?
I don't think this should be an error

**Comment by abrden** [comment]
Endpoint `POST /tracks/{trackId}/popularity` [returns a rate](http://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/NickCis/24b3922f204af2f44d85fae927fc6dc5/raw/975b713824b728a85d80a9ab1c11c5b7f367faf8/music-shared-api.yaml#null%2Fpaths%2F~1tracks~1%7BtrackId%7D~1popularity%2Fpost), is it the general track rating or the one the user just gave? @saantiaguilera

**Comment by abrden** [comment]
Doc's `/me/tracks/favorites` route moved to `/api/tracks/me/favorites`
